
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
